### ISSUE TITLE
I love this site! Very useful stats for hypixel.

### ISSUE THREAD

**Issue by philsarisk** [RealCyGuy/UsefulHypixelStats#1]

**Comment by RealCyGuy** [comment]
noo it's very useful with the stats you care about

**Comment by philsarisk** [comment]
how did u make it

**Comment by RealCyGuy** [comment]
Here, I put the source code on GitHub for you. [Go check it out!](https://github.com/RealCyGuy/UsefulHypixelStats)

**Comment by philsarisk** [comment]
> Here, I put the source code on GitHub for you. [Go check it out!](https://github.com/RealCyGuy/UsefulHypixelStats)

THANKS VERY HELPFUL ☺️😊

**Comment by RealCyGuy** [comment]
You're welcome! 👌 ❤️ 👏
